# Generated by Django 4.0.6 on 2022-07-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfolio_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
