# Generated by Django 4.0.6 on 2022-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_category_owner_remove_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image', upload_to='images/posts/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='image', upload_to='images/portfolio/'),
        ),
    ]
