# Generated by Django 4.0.6 on 2022-07-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_service_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
    ]
